#!/bin/sh
modname=vnic
devname=Supervisor
mod=`ls  /dev/ | grep $devname`
echo $mod
if [ "$mod" == "" ]; then
	echo No device file
else
	echo remove device file /dev/$mod
	rm -f /dev/$mod
fi
rmmod $modname
	
